apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy
  namespace: istio-test
  labels:
    app: mitmproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitmproxy
  template:
    metadata:
      labels:
        app: mitmproxy
    spec:
      containers:
      - name: mock-service
        image: python:3.11-slim
        command:
          - python3
          - /scripts/server.py
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: mock-service-script
          mountPath: /scripts
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: mock-service-script
        configMap:
          name: mock-service-script
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: mitmproxy
  namespace: istio-test
  labels:
    app: mitmproxy
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mitmproxy
