apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy
  namespace: istio-test
  labels:
    app: mitmproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitmproxy
  template:
    metadata:
      labels:
        app: mitmproxy
    spec:
      containers:
      - name: mitmproxy
        image: mitmproxy/mitmproxy:latest
        command:
          - mitmdump
          - --mode
          - regular
          - --showhost
          - --listen-host
          - "0.0.0.0"
          - --listen-port
          - "8080"
          - -s
          - /scripts/proxy_addon.py
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: mitmproxy-script
          mountPath: /scripts
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: mitmproxy-script
        configMap:
          name: mitmproxy-script
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: mitmproxy
  namespace: istio-test
  labels:
    app: mitmproxy
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mitmproxy
