apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-intercept
  namespace: istio-test
spec:
  hosts:
  - httpbin.org
  http:
  # Route 1: If X-Intercept header is present, route to mitmproxy
  - match:
    - headers:
        X-Intercept:
          exact: "true"
    route:
    - destination:
        host: mitmproxy.istio-test.svc.cluster.local
        port:
          number: 8080
  # Route 2: Default route to external httpbin.org
  - route:
    - destination:
        host: httpbin.org
        port:
          number: 80
